# Generated by Django 5.0.1 on 2024-02-19 23:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ticket_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, spaces, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[api.models.CustomUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
