import os

SECRET_KEY = os.getenv('SECRET_KEY')
SECRET_DB_NAME = os.getenv('DB_NAME')
SECRET_DB_USER = os.getenv('DB_USER')
SECRET_DB_PASSWORD = os.getenv('DB_PASSWORD')
SECRET_DB_HOST = os.getenv('DB_HOST')
SECRET_DB_PORT = os.getenv('DB_PORT')
SECRET_AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
SECRET_AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
SECRET_AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
