#############################
#                           #
#         Usuários          #
#                           #
#############################

# Listagem de usuários
GET http://127.0.0.1:8000/api/v1/usuarios/?username=ad
Authorization: Token <SEU-TOKEN-AQUI>

###

# Registro de usuário
POST http://127.0.0.1:8000/api/v1/usuarios/registrar
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

{
  "username": "novousuario",
  "password": "senha",
  "email": "novousuario@example.com"
}

###

# Login de usuário
POST http://127.0.0.1:8000/api/v1/usuarios/auth/token/login
Content-Type: application/json

{
  "email": "novousuario@example.com",
  "password": "senha"
}

###

# Info do usuário atual
GET http://127.0.0.1:8000/api/v1/usuarios/auth/users/me/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

###

# Logout de usuário
POST http://127.0.0.1:8000/api/v1/usuarios/auth/logout
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

###

# Editar usuário
POST http://127.0.0.1:8000/api/v1/usuarios/auth/token/login
Content-Type: application/json

{
  "username": "nomedousuario",
  "email": "novousuario@example.com",
  "is_active": true,
  "password": "senha"
}

###

# Desativar usuário
DELETE  http://127.0.0.1:8000/api/v1/usuarios/deletar/1/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

###

#############################
#                           #
#           Planos          #
#                           #
#############################

# Listar planos
GET http://127.0.0.1:8000/api/v1/planos/

###

# Criar plano
POST http://127.0.0.1:8000/api/v1/planos/criar
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

{
  "name": "Plano Avançado",
  "value": 99.90,
  "benefits": [1, 2, 3]
}

###

# Editar plano
PUT http://127.0.0.1:8000/api/v1/planos/editar/1/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

{
  "name": "novo nome plano",
  "value": 499.90,
  "benefits": [4, 5, 6]
}

###

# Deletar plano
DELETE  http://127.0.0.1:8000/api/v1/planos/deletar/1/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

###

#############################
#                           #
#   Benefícios dos planos   #
#                           #
#############################

# Listagem de benefícios
GET http://127.0.0.1:8000/api/v1/planos/beneficios/

###

# Criar benefício
POST http://127.0.0.1:8000/api/v1/planos/beneficios/criar/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

{
  "name": "nome do beneficio",
  "description": "descricao do beneficio"
}

###

# Editar benefício
PUT http://127.0.0.1:8000/api/v1/planos/beneficios/editar/1/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

{
  "name": "novo nome do beneficio",
  "description": "nova descricao do beneficio"
}

###

# Deletar benefício
DELETE  http://127.0.0.1:8000/api/v1/planos/beneficios/deletar/1/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

###

#############################
#                           #
#        Assinaturas        #
#                           #
#############################

# Listagem de assinaturas
GET http://127.0.0.1:8000/api/v1/assinaturas/
Authorization: Token <SEU-TOKEN-AQUI>

###

# Criar assinatura
POST http://127.0.0.1:8000/api/v1/assinaturas/criar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token <SEU-TOKEN-AQUI>

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"

1
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plan"

1
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="contract"; filename="example.pdf"
Content-Type: application/pdf

< ./example.pdf

----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Editar assinatura
PUT http://127.0.0.1:8000/api/v1/assinaturas/editar/1/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token <SEU-TOKEN-AQUI>

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plan"

2
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="contract"; filename="new-example.pdf"
Content-Type: application/pdf

< ./new-example.pdf

----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Deletar assinatura
DELETE  http://127.0.0.1:8000/api/v1/assinaturas/deletar/3
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

###

#############################
#                           #
#        Localidades        #
#                           #
#############################

# Listagem de localidades
GET http://127.0.0.1:8000/api/v1/localidades/

###

# Criar localidade
POST http://127.0.0.1:8000/api/v1/localidades/criar/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

{
  "city": "nova cidade localidade",
  "state": "novo estado localidade"
}

###

# Editar localidade
PUT http://127.0.0.1:8000/api/v1/localidades/editar/1/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

{
  "city": "novo nome cidade localidade",
  "state": "novo nome estado localidade"
}

###

# Deletar localidade
DELETE  http://127.0.0.1:8000/api/v1/localidades/deletar/1/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

###

#############################
#                           #
#          Boletos          #
#                           #
#############################

# Listar boletos
GET http://127.0.0.1:8000/api/v1/boletos/
Authorization: Token <SEU-TOKEN-AQUI>

###

# Criar boleto
POST http://127.0.0.1:8000/api/v1/boletos/criar/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token <SEU-TOKEN-AQUI>

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="signature"

1
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="expire_date"

01-01-2024
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document"; filename="example.pdf"
Content-Type: application/pdf

< ./example.pdf

----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Editar boleto
PUT http://127.0.0.1:8000/api/v1/boletos/editar/1/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token <SEU-TOKEN-AQUI>

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="expire_date"

03-02-2024
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document"; filename="new-example.pdf"
Content-Type: application/pdf

< ./new-example.pdf

----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Deletar boleto
DELETE  http://127.0.0.1:8000/api/v1/boletos/deletar/1/
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

###

#############################
#                           #
#  Endpoints dos clientes   #
#                           #
#############################

# Alteração de Senha do cliente
PUT http://127.0.0.1:8000/api/v1/cliente/senha/alterar
Content-Type: application/json
Authorization: Token <SEU-TOKEN-AQUI>

{
  "old_password": "senhadonovousuario",
  "new_password": "senha"
}

###

# Listar assinaturas do cliente
GET http://127.0.0.1:8000/api/v1/cliente/assinaturas
Authorization: Token <SEU-TOKEN-AQUI>

###

# Listar boletos do cliente
GET http://127.0.0.1:8000/api/v1/cliente/boletos
Authorization: Token <SEU-TOKEN-AQUI>

###
