@authorization = <seu-token-aqui>
@protocol = https
@hostname = veloxnet-back.vercel.app
@host = {{hostname}}

###

#############################
#                           #
#         Usuários          #
#                           #
#############################

# Listagem de usuários
GET {{protocol}}://{{host}}/api/v1/usuarios/
Authorization: Token {{authorization}}

###

# Registro de usuário
POST {{protocol}}://{{host}}/api/v1/usuarios/registrar
Content-Type: application/json
Authorization: Token {{authorization}}

{
  "username": "novousuario",
  "password": "senha",
  "email": "novousuario@example.com"
}

###

# Login de usuário
POST {{protocol}}://{{host}}/api/v1/usuarios/auth/token/login
Content-Type: application/json

{
  "email": "usuario@veloxnet.com",
  "password": "senhadousuario"
}

###

# Info do usuário atual
GET {{protocol}}://{{host}}/api/v1/usuarios/auth/users/me/
Content-Type: application/json
Authorization: Token {{authorization}}

###

# Logout de usuário
POST {{protocol}}://{{host}}/api/v1/usuarios/auth/logout
Content-Type: application/json
Authorization: Token {{authorization}}

###

# Editar usuário
PUT {{protocol}}://{{host}}/api/v1/usuarios/editar/2
Content-Type: application/json
Authorization: Token {{authorization}}

{
  "username": "nomedousuario",
  "email": "novousuario@example.com",
  "is_active": true,
  "password": "senha"
}

###

# Desativar usuário
DELETE  {{protocol}}://{{host}}/api/v1/usuarios/deletar/2
Content-Type: application/json
Authorization: Token {{authorization}}

###

#############################
#                           #
#           Planos          #
#                           #
#############################

# Listar planos
GET {{protocol}}://{{host}}/api/v1/planos/

###

# Criar plano
POST {{protocol}}://{{host}}/api/v1/planos/criar
Content-Type: application/json
Authorization: Token {{authorization}}

{
  "name": "Plano Avançado",
  "value": 99.90,
  "benefits": [1, 2, 3]
}

###

# Editar plano
PUT {{protocol}}://{{host}}/api/v1/planos/editar/1
Content-Type: application/json
Authorization: Token {{authorization}}

{
  "name": "novo nome do plano",
  "value": 499.90,
  "benefits": [4, 5, 6]
}

###

# Deletar plano
DELETE  {{protocol}}://{{host}}/api/v1/planos/deletar/1
Content-Type: application/json
Authorization: Token {{authorization}}

###

#############################
#                           #
#   Benefícios dos planos   #
#                           #
#############################

# Listagem de benefícios
GET {{protocol}}://{{host}}/api/v1/planos/beneficios/

###

# Criar benefício
POST {{protocol}}://{{host}}/api/v1/planos/beneficios/criar
Content-Type: application/json
Authorization: Token {{authorization}}

{
  "name": "Suporte 24H",
  "description": "Suporte o tempo todo"
}

###

# Editar benefício
PUT {{protocol}}://{{host}}/api/v1/planos/beneficios/editar/1
Content-Type: application/json
Authorization: Token {{authorization}}

{
  "name": "novo nome do beneficio",
  "description": "nova descricao do beneficio"
}

###

# Deletar benefício
DELETE  {{protocol}}://{{host}}/api/v1/planos/beneficios/deletar/1
Content-Type: application/json
Authorization: Token {{authorization}}

###

#############################
#                           #
#        Assinaturas        #
#                           #
#############################

# Listagem de assinaturas
GET {{protocol}}://{{host}}/api/v1/assinaturas/
Authorization: Token {{authorization}}

###

# Criar assinatura 
#! Não está funcionando por aqui porque a extensão Rest Client identifica os
#! argumentos de número como string. Portanto vai dar erro, por exemplo, no user
#! porque a api espera um inteiro com o id e não uma string.
POST {{protocol}}://{{host}}/api/v1/assinaturas/criar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token {{authorization}}

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"

1
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plan"

1
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="contract"; filename="test_document.pdf"
Content-Type: application/pdf

< ./test_document.pdf

----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Editar assinatura
PUT {{protocol}}://{{host}}/api/v1/assinaturas/editar/1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token {{authorization}}

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="plan"

2
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="contract"; filename="test_document.pdf"
Content-Type: application/pdf

< ./test_document.pdf

----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Deletar assinatura
DELETE  {{protocol}}://{{host}}/api/v1/assinaturas/deletar/1
Content-Type: application/json
Authorization: Token {{authorization}}

###

#############################
#                           #
#        Localidades        #
#                           #
#############################

# Listagem de localidades
GET {{protocol}}://{{host}}/api/v1/localidades/

###

# Criar localidade
POST {{protocol}}://{{host}}/api/v1/localidades/criar
Content-Type: application/json
Authorization: Token {{authorization}}

{
  "city": "nova cidade localidade",
  "state": "novo estado localidade"
}

###

# Editar localidade
PUT {{protocol}}://{{host}}/api/v1/localidades/editar/1
Content-Type: application/json
Authorization: Token {{authorization}}

{
  "city": "novo nome cidade localidade",
  "state": "novo nome estado localidade"
}

###

# Deletar localidade
DELETE  {{protocol}}://{{host}}/api/v1/localidades/deletar/1
Content-Type: application/json
Authorization: Token {{authorization}}

###

#############################
#                           #
#          Boletos          #
#                           #
#############################

# Listar boletos
GET {{protocol}}://{{host}}/api/v1/boletos/
Authorization: Token {{authorization}}

###

# Criar boleto
POST {{protocol}}://{{host}}/api/v1/boletos/criar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token {{authorization}}

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="signature"

1
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="expire_date"

2024-03-15
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document"; filename="test_document.pdf"
Content-Type: application/pdf

< ./test_document.pdf

----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Editar boleto
PUT {{protocol}}://{{host}}/api/v1/boletos/editar/1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token {{authorization}}

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="expire_date"

2024-03-15
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="signature"

1
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document"; filename="test_document.pdf"
Content-Type: application/pdf

< ./test_document.pdf

----WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Deletar boleto
DELETE  {{protocol}}://{{host}}/api/v1/boletos/deletar/1
Content-Type: application/json
Authorization: Token {{authorization}}

###

#############################
#                           #
#  Endpoints dos clientes   #
#                           #
#############################

# Alteração de Senha do cliente
PUT {{protocol}}://{{host}}/api/v1/cliente/senha/alterar
Content-Type: application/json
Authorization: Token {{authorization}}

{
  "old_password": "senhadonovousuario",
  "new_password": "senha"
}

###

# Listar assinaturas do cliente
GET {{protocol}}://{{host}}/api/v1/cliente/assinaturas
Authorization: Token {{authorization}}

###

# Listar boletos do cliente
GET {{protocol}}://{{host}}/api/v1/cliente/boletos
Authorization: Token {{authorization}}

###
